### ISSUE TITLE
Other sprite for the lamp when no electricity

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#120]
"Blackout - aber die Lampe ist an?!" -> We already talked about the idea for another sprite. Did we scrap it? Not sure.

**Comment by marCOmics** [comment]
Oh, I forgot about it LOL.

**Comment by marCOmics** [comment]
No time to do this. The sprite and general "replace furniture"-function already exists, but the problem is, that it takes more time to think about all the edge cases, as you have to design a good solution that replaces energy-dependent sprites with their energy-off-versions each time the period/day changes and you're at home.. :p
