### ISSUE TITLE
Missing Avatar-Picture of Veronika when trading

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#148]
"wenn Handel mit Veronika fehlschlägt hat sie für ein Dialogfeld kein Avatarbild"

**Comment by marCOmics** [comment]
This is the case with most NPCs. The easiest solution is to ensure that after each "~ BRANCH" (or other tag) a normal dialogue lines is in the first position, not an actual dialogue branch with different answer options. So writing
`~ BRANCH
Veronika: <Neuer Text, z.B. Und?>
- Option 1
- Option 2
- ...`
will fix the issue

I'm not sure if we can remedy that easily, otherwise.

**Comment by Spexify** [comment]
We now have a new Trading system 0d95e9a3c4e2ff4c97e827875e9323c2f91e8bfb
